// Generated by CoffeeScript 1.8.0
var Food,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Food = (function(_super) {
  __extends(Food, _super);

  Food.prototype.color = "#7e7";

  function Food(game) {
    this.game = game;
    this.spawn();
    this.draw();
  }

  Food.prototype.spawn = function() {
    var free, ok;
    ok = false;
    free = intersec_arrays(this.game.map.points, this.game.snake.points, arr_comp);
    if (free.length > 0) {
      this.points = [free[random_int(1, free.length - 1)]];
      return log("food at [" + this.points[0] + "]");
    } else {
      this.game.over = true;
      return log("game finished, snake has max size");
    }
  };

  Food.prototype.remove = function() {
    this.draw(this.points, this.game.map.color);
    return this.points = [];
  };

  Food.prototype.respawn = function() {
    this.remove();
    return this.spawn();
  };

  return Food;

})(GameObject);
