// Generated by CoffeeScript 1.8.0
var Game,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

Game = (function() {
  Game.prototype.ESC = [27, 13, 32];

  Game.prototype.LEFT = [37, 65];

  Game.prototype.RIGHT = [39, 68];

  Game.prototype.UP = [38, 87];

  Game.prototype.DOWN = [40, 83];

  function Game(width, height, size, speed) {
    this.width = width != null ? width : 30;
    this.height = height != null ? height : 30;
    this.size = size != null ? size : 12;
    if (speed == null) {
      speed = 5;
    }
    this.over = false;
    this.wrapper = $("game");
    this.canvas = $("game_canvas");
    if (this.canvas != null) {
      this.canvas.remove();
    }
    this.canvas = document.createElement("canvas");
    this.canvas.setAttribute("id", "game_canvas");
    this.wrapper.appendChild(this.canvas);
    this.msg = new Message;
    this.speed = new Speed(this, speed);
    this.score = new Score(this);
    this.map = new Map(this);
    this.snake = new Snake(this);
    this.food = new Food(this);
    window.captureEvents(Event.KEYPRESS);
    window.onkeydown = this.interupt.bind(this);
    this.stop();
  }

  Game.prototype.interupt = function(e) {
    var key;
    e = e || window.event;
    key = e.which;
    if (this.over) {
      if (key === 82) {
        this["new"]();
      }
    } else {
      if (__indexOf.call(this.ESC, key) >= 0) {
        if (this.started) {
          this.stop();
        } else {
          this.start();
        }
      }
      if (__indexOf.call(this.LEFT, key) >= 0) {
        this.snake.turn_left();
      }
      if (__indexOf.call(this.RIGHT, key) >= 0) {
        this.snake.turn_right();
      }
      if (!this.started) {
        if (__indexOf.call(this.UP, key) >= 0) {
          this.speed.up();
        }
        if (__indexOf.call(this.DOWN, key) >= 0) {
          this.speed.down();
        }
      }
    }
  };

  Game.prototype.stop = function() {
    this.msg.show("Press <b>Space/Enter/Esc</b> to start");
    clearInterval(this.interval);
    this.started = false;
  };

  Game.prototype.start = function() {
    this.interval = setInterval(this.main_loop.bind(this), 1000 / this.speed.value / 2);
    this.started = true;
    this.msg.hide();
  };

  Game.prototype.main_loop = function() {
    this.snake.move();
    this.snake.draw();
    this.food.draw();
  };

  Game.prototype["new"] = function(width, height, size, speed) {
    if (width == null) {
      width = this.width;
    }
    if (height == null) {
      height = this.height;
    }
    if (size == null) {
      size = this.size;
    }
    if (speed == null) {
      speed = this.speed.value;
    }
    this.stop();
    return this.constructor(width, height, size, speed);
  };

  return Game;

})();
