// Generated by CoffeeScript 1.8.0
window.onload = function() {
  window.game = new Game(40, 30, 14);
  game.SPEED = 10;
  game.interupt();
};

window.captureEvents(Event.KEYPRESS);

window.onkeydown = pressed;
