// Generated by CoffeeScript 1.8.0
var Message;

Message = (function() {
  function Message() {
    this.tag = $("msg");
  }

  Message.prototype.show = function(text) {
    this.text = text;
    this.tag.innerHTML = this.text;
    this.hide();
    return this.tag.setAttribute("class", "msg_show");
  };

  Message.prototype.hide = function() {
    return this.tag.setAttribute("class", "msg_hide");
  };

  return Message;

})();
