// Generated by CoffeeScript 1.8.0
var Message;

Message = (function() {
  function Message(tag) {
    this.tag = tag;
  }

  Message.prototype.show = function(text) {
    this.text = text;
    this.tag.textContent = this.text;
    this.hide();
    return this.tag.setAttribute("class", "msg_show");
  };

  Message.prototype.hide = function() {
    return this.tag.setAttribute("class", "msg_hide");
  };

  return Message;

})();
