// Generated by CoffeeScript 1.8.0
var Score;

Score = (function() {
  function Score(game) {
    this.game = game;
    this.tag = $("score");
    this.value = 0;
    this.tag.textContent = this.value;
  }

  Score.prototype.next = function() {
    this.value += this.game.speed.value;
    return this.tag.textContent = this.value;
  };

  return Score;

})();
