// Generated by CoffeeScript 1.8.0
var Speed;

Speed = (function() {
  function Speed(game, value) {
    this.game = game;
    this.value = value;
    this.tag = $("speed");
    this.show();
  }

  Speed.prototype.show = function() {
    return this.tag.textContent = this.value;
  };

  Speed.prototype.up = function() {
    if (!(this.value >= 30)) {
      this.value++;
      return this.show();
    }
  };

  Speed.prototype.down = function() {
    if (!(this.value <= 1)) {
      this.value--;
      return this.show();
    }
  };

  return Speed;

})();
